default:
  image: node:18

.deploy:
  rules:
  except:
  - schedules
  variables:
    VERCEL_ORG_ID: $VERCEL_ORG_ID
    VERCEL_PROJECT_ID: $VERCEL_ORDBOKENE_PROJECT_ID
    VERCEL_TOKEN: $VERCEL_TOKEN_HENRIK
    VERCEL_PRESET: vercel
  script:
  - curl -L https://git.app.uib.no/api/v4/projects/16442/jobs/artifacts/${INFLECTION_VERSION}/raw/components.tar.gz?job=publish_vue3 | tar xz
  - npm install --global vercel
  - vercel pull --yes --environment=$ENVIRONMENT --token=$VERCEL_TOKEN
  - vercel build --token=$VERCEL_TOKEN $([ "$ENVIRONMENT" = "production" ] && echo "--prod") 
  - vercel deploy --prebuilt $([ "$ENVIRONMENT" = "production" ] && echo "--prod") --token=$VERCEL_TOKEN
                  -m gitlabDeployment="1"
                  -m gitlabCommitAuthorName="${CI_COMMIT_AUTHOR}"
                  -m gitlabCommitMessage="${CI_COMMIT_MESSAGE}"
                  -m gitlabCommitOrg="${CI_PROJECT_NAMESPACE}"
                  -m gitlabCommitRef="${CI_COMMIT_REF_NAME}"
                  -m gitlabCommitRepo="ordbokene-nuxt"
                  -m gitlabCommitSha="${CI_COMMIT_SHA}"
                  -m gitlabOrg="https://git.app.uib.no/"
                  -m gitlabRepo="ordbokene-nuxt"
                  -m gitlabCommitAuthorLogin="${GITLAB_USER_LOGIN}"
  tags:
    - group_runner_spraaksamlingene_01


vercel_preview_dev:
  extends: .deploy
  stage: preview
  except: 
  - main
  - schedules
  variables:
    ENVIRONMENT: preview
    INFLECTION_VERSION: 1.2.3


.main-branch:
  extends: .deploy
  only: 
  - main
  variables:
    INFLECTION_VERSION: 1.2.3


vercel_preview_main:
  extends: .main-branch
  stage: preview
  variables:
    ENVIRONMENT: preview


vercel_prod_main:
  extends: .main-branch
  stage: prod
  when: manual
  variables:
    ENVIRONMENT: production